### ISSUE TITLE
CLI-only version?

### ISSUE THREAD

**Issue by rwjack** [muammar/mkchromecast#381]
Trying to install in a docker container -

Dockerfile:
```
FROM debian:stable
RUN apt update && apt install -y mkchromecast
```
docker-compose.yml:
```
 mkchromecast:
    image: local/mkchromecast:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: mkchromecast -t
    restart: unless-stopped

```

Error log:
```
qt.qpa.xcb: could not connect to display 

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

Is there a CLI only version I can use on my headless server? Basically trying to stream media from my server to the TV.
